apiVersion: v1
kind: Service
metadata:
  name: petclinic-demo-service
spec:
  selector:
    app: petclinic-demo
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: petclinic-demo
    protocol: TCP
    port: 80