namespace: dev
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: fc887e6d92f1ff2487d4e72ec2a07a7b94a7e3e1
resources:
- ../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
