namespace: dev
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: 1ace9db4e396b3a5b70652f5323b3cd806d62274
resources:
- ../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
